# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Codigo para manejar ambientes y el codigo necesario


# Define el comando por defecto para ejecutar la aplicación
CMD ["python", "app.py"]